const allGuestsAndTable = [
  {
    table1: [
      "Olufunke Elutilo",
      "Temidayo Elutilo",
      "Samson Amosu",
      "Feyi Amosu",
      "Adeola Duroshola",
      "Tope Duroshola",
      "Wole Soluade",
      "Taye Soluade",
      "Demola Ipaye",
      "Seun Ipaye",
    ],
  },
  {
    table2: [
      "Folake Ojutalayo",
      "Nurudeen Duroshola",
      "Kayode Duroshola",
      "Herietta Duroshola",
      "Gbenga Duroshola",
      "Funlola Duroshola",
      "Jumoke Johnson",
      "Bisi Ketiku",
      "Nnenna Kalejaye",
    ],
  },
  {
    table3: [
      "Iyabo Idowu ",
      "Joke Olaniyi",
      "Olumuyiwa Olaniyi",
      "Bimbola Olanrewaju",
      "Comfort  Odhomi",
      "Victor Odhomi",
      "Toyin Komolafe ",
      "Mrs Ronke Oni ",
      "Olukolade Komolafe",
      "Margaret Jimbola",
    ],
  },
  {
    table4: [
      "Adewunmi Akinsanya",
      "Kenny Animashaun",
      "Joke Sokunbi",
      "Labake Oladunjoy",
      "Olanrewaju Onasoga",
      "Joke Onasoga",
      "Funmi Esan",
      "Sola Ajayi",
      "Bola Tijani",
      "Bola Adetoro",
    ],
  },
  {
    table5: [
      "Kk",
      "Kunbi KK",
      "Jide Ademujimi",
      "Shola Adigun",
      "Helen Thomas",
      "Jennifer Ifanse",
      "Dayo Adeoye",
      "Sola Awosika",
      "Fola Allison",
    ],
  },
  {
    table6: [
      "Ola Duroshola",
      "Lola Duroshola",
      "Bola Ikupoluyi",
      "Bisi Ikupoluyi",
      "Bolaji Elias",
      "Bolanle Elias",
      "Dele Osisami",
      "Trier Harris",
      "Demola Lantinwo",
      "Foluke Lantinwo",
    ],
  },
  {
    table7: [
      "Adekunle Adebola",
      "Olumuyiwa Oke",
      "Felicia Lewis",
      "Funlola Adigun",
      "Sola Adebayo",
    ],
  },
  {
    table8: [
      "Saeedat Oladunjoye",
      "Tope Elutilo",
      "Aminata Lewis",
      "Deborah Duroshola",
      "David Duroshola",
      "Daniella Duroshola",
      "Tayo Akintoye",
      "Ayomipo Ojutalayo",
    ],
  },
  {
    table9: [
      "Erin Duroshola",
      "Tosin Osinuga",
      "Jimi Ipaye",
      "Temilayo Ipaye",
      "Jimi Duroshola",
      "Emmanuel Soluade",
      "John Soluade",
      "Joshua Soluade",
      "Seun Osinuga",
      "Jade Duroshola",
      "Happyness Okonwo",
    ],
  },
];

export default allGuestsAndTable;
